CREATE TABLE MEMBER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    member_name VARCHAR(50) NOT NULL,
    phone VARCHAR(20),
    role VARCHAR(20) DEFAULT 'MEMBER' CHECK (role IN ('ADMIN', 'MEMBER')),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'WITHDRAWN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UK_MEMBER_LOGIN_ID UNIQUE (login_id)
);

CREATE TABLE COHORT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    generation VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UK_COHORT_GENERATION UNIQUE (generation)
);

CREATE TABLE PART (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    part_name VARCHAR(50) NOT NULL,
    FOREIGN KEY (cohort_id) REFERENCES COHORT(id)
);

CREATE TABLE TEAM (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    team_name VARCHAR(50) NOT NULL,
    FOREIGN KEY (cohort_id) REFERENCES COHORT(id)
);

CREATE TABLE COHORT_MEMBER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    member_id BIGINT NOT NULL,
    cohort_id BIGINT NOT NULL,
    part_id BIGINT,
    team_id BIGINT,
    deposit INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    FOREIGN KEY (member_id) REFERENCES MEMBER(id),
    FOREIGN KEY (cohort_id) REFERENCES COHORT(id),
    FOREIGN KEY (part_id) REFERENCES PART(id),
    FOREIGN KEY (team_id) REFERENCES TEAM(id),
    CONSTRAINT UK_MEMBER_COHORT UNIQUE (member_id, cohort_id) -- 한 기수에 중복 가입 방지
);

CREATE TABLE SESSION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    session_date DATE NOT NULL,
    session_time TIME NOT NULL,
    session_location VARCHAR(255),
    session_status VARCHAR(20) DEFAULT 'SCHEDULED' CHECK (session_status IN ('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cohort_id) REFERENCES COHORT(id)
);

CREATE TABLE QR_CODE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT NOT NULL,
    hash_value VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (session_id) REFERENCES SESSION(id),
    CONSTRAINT UK_QR_HASH_VALUE UNIQUE (hash_value)
);

CREATE TABLE ATTENDANCE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    session_id BIGINT NOT NULL,
    qr_code_id BIGINT NOT NULL,
    cohort_member_id BIGINT NOT NULL,
    attendance_status VARCHAR(20) NOT NULL CHECK (status IN ('PRESENT', 'LATE', 'ABSENT', 'EXCUSED')),
    late_minutes INT DEFAULT 0,
    penalty_amount INT DEFAULT 0,
    reason VARCHAR(255),
    checked_in_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (session_id) REFERENCES SESSION(id),
    FOREIGN KEY (cohort_member_id) REFERENCES COHORT_MEMBER(id),
    CONSTRAINT UK_ATTENDANCE_SESSION_COHORT_MEMBER UNIQUE (session_id, cohort_member_id)
);

CREATE TABLE DEPOSIT_HISTORY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cohort_member_id BIGINT NOT NULL,
    attendance_id BIGINT,
    deposit_type VARCHAR(20) NOT NULL CHECK (deposit_type IN ('INITIAL', 'PENALTY', 'REFUND')),
    deposit_amount INT NOT NULL,
    balance_after INT NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cohort_member_id) REFERENCES COHORT_MEMBER(id),
    FOREIGN KEY (attendance_id) REFERENCES ATTENDANCE(id)
);